version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: ice-party-watcher
    docker:
      - image: cimg/node:14.17.3
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-main:
    jobs:
      - build:
          filters:
            branches:
              only: main
