version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: ray888/ice-party-watcher
    docker:
      - image: cimg/node:14.17.3
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:0.1.0 .

      - run:
          name: Publish Docker image
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $IMAGE_NAME:0.1.0 

workflows:
  version: 2
  build-main:
    jobs:
      - build:
          filters:
            branches:
              only: main
